#!/usr/bin/env node
/**
 * build-data.js — composes data/dashboard-data.js from data/sources/*.json
 *
 * Contract: this script must NEVER throw and must ALWAYS emit a valid
 * dashboard-data.js, whatever state data/sources/ is in. A source that is
 * missing, unparseable, or malformed becomes an "offline" envelope; the
 * page renders it as an offline card instead of breaking.
 *
 * Envelope shape (one per source file):
 *   { source, label, status: "online"|"offline", fetched_at, error, data }
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'data', 'sources');
const OUT_FILE = path.join(ROOT, 'data', 'dashboard-data.js');

// Every source the dashboard knows how to render, in display order.
// briefing is the AI morning briefing; the rest are live tool probes.
const EXPECTED = [
  { name: 'briefing', label: 'AI Morning Briefing' },
  { name: 'calendar', label: 'Schedule' },
  { name: 'gmail', label: 'Inbox Signals' },
  { name: 'tactiq', label: 'Meeting Intelligence' },
  { name: 'snitcher', label: 'Website Visitor Intel' },
  { name: 'hubspot', label: 'Sales Pipeline' },
  { name: 'quickbooks', label: 'Finance' },
  { name: 'apollo', label: 'Outbound Engine' },
  { name: 'drive', label: 'Workspace Docs' },
];

function offlineEnvelope(name, label, reason) {
  return {
    source: name,
    label,
    status: 'offline',
    fetched_at: null,
    error: reason,
    data: null,
  };
}

function readEnvelope({ name, label }) {
  const file = path.join(SRC_DIR, `${name}.json`);
  let raw;
  try {
    raw = fs.readFileSync(file, 'utf8');
  } catch {
    return offlineEnvelope(name, label, 'No data file — source has not been refreshed.');
  }
  let env;
  try {
    env = JSON.parse(raw);
  } catch (e) {
    return offlineEnvelope(name, label, `Data file is not valid JSON (${e.message}).`);
  }
  if (!env || typeof env !== 'object' || Array.isArray(env)) {
    return offlineEnvelope(name, label, 'Data file is not an envelope object.');
  }
  env.source = name;
  env.label = typeof env.label === 'string' && env.label ? env.label : label;
  if (env.status !== 'online') {
    env.status = 'offline';
    env.data = env.data ?? null;
    env.error = typeof env.error === 'string' && env.error ? env.error : 'Source reported offline.';
  } else if (env.data == null || typeof env.data !== 'object') {
    env.status = 'offline';
    env.data = null;
    env.error = env.error || 'Source reported online but returned no data.';
  }
  if (typeof env.fetched_at !== 'string') env.fetched_at = null;
  if (env.error != null && typeof env.error !== 'string') env.error = String(env.error);
  return env;
}

fs.mkdirSync(SRC_DIR, { recursive: true });

const sources = {};
for (const spec of EXPECTED) sources[spec.name] = readEnvelope(spec);

const online = Object.values(sources).filter((s) => s.status === 'online');
const payload = {
  generated_at: new Date().toISOString(),
  online_count: online.length,
  source_count: EXPECTED.length,
  sources,
};

const banner =
  '// GENERATED by scripts/build-data.js — do not edit by hand.\n' +
  '// Rebuild with: node scripts/build-data.js\n';
fs.writeFileSync(OUT_FILE, banner + 'window.MISSION_CONTROL = ' + JSON.stringify(payload, null, 2) + ';\n');

for (const s of Object.values(sources)) {
  const mark = s.status === 'online' ? 'ONLINE ' : 'offline';
  console.log(`  [${mark}] ${s.source.padEnd(10)} ${s.error ? '— ' + s.error : ''}`);
}
console.log(`Wrote ${path.relative(ROOT, OUT_FILE)} (${online.length}/${EXPECTED.length} sources online)`);
